<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1//EN" "http://www.w3.org/TR/xhtml11/DTD/xhtml11.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8" />
<title>Control de Materias</title>
<link rel="shortcut icon" type="image/x-icon" href="favicon.ico" />
<link rel="stylesheet" type="text/css" href="<?= $this->baseUrl('style') ?>/default.css" media="all" />
</head>
<body>
<div id="menu">
<ul class="menu" id="left">
<li><a href="http://untrefcomputacion.com.ar" target="_blank" class="blink">untrefcomputación.com.ar</a></li>
</ul>
<ul class="menu" id="right">
<li><a href="<?= $this->baseUrl('auth/login') ?>">Iniciar sesión</a></li>
<li><a href="<?= $this->baseUrl('auth/registracion') ?>">Registrarse</a></li>
</ul>
</div>
<div id="contentAuth">
<?php echo $this->layout()->content; ?>    
</div>

</body>
</html>
